// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloaders

import (
	"sync"
	"time"

	"gogql/app/models/dbmodels"
)

// DepartmentLoaderConfig captures the config to create a new DepartmentLoader
type DepartmentLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []int64) ([]*dbmodels.Department, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewDepartmentLoader creates a new DepartmentLoader given a fetch, wait, and maxBatch
func NewDepartmentLoader(config DepartmentLoaderConfig) *DepartmentLoader {
	return &DepartmentLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// DepartmentLoader batches and caches requests
type DepartmentLoader struct {
	// this method provides the data for the loader
	fetch func(keys []int64) ([]*dbmodels.Department, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[int64]*dbmodels.Department

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *departmentLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type departmentLoaderBatch struct {
	keys    []int64
	data    []*dbmodels.Department
	error   []error
	closing bool
	done    chan struct{}
}

// Load a Department by key, batching and caching will be applied automatically
func (l *DepartmentLoader) Load(key int64) (*dbmodels.Department, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a Department.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *DepartmentLoader) LoadThunk(key int64) func() (*dbmodels.Department, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (*dbmodels.Department, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &departmentLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (*dbmodels.Department, error) {
		<-batch.done

		var data *dbmodels.Department
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *DepartmentLoader) LoadAll(keys []int64) ([]*dbmodels.Department, []error) {
	results := make([]func() (*dbmodels.Department, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	departments := make([]*dbmodels.Department, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		departments[i], errors[i] = thunk()
	}
	return departments, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Departments.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *DepartmentLoader) LoadAllThunk(keys []int64) func() ([]*dbmodels.Department, []error) {
	results := make([]func() (*dbmodels.Department, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]*dbmodels.Department, []error) {
		departments := make([]*dbmodels.Department, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			departments[i], errors[i] = thunk()
		}
		return departments, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *DepartmentLoader) Prime(key int64, value *dbmodels.Department) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := *value
		l.unsafeSet(key, &cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *DepartmentLoader) Clear(key int64) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *DepartmentLoader) unsafeSet(key int64, value *dbmodels.Department) {
	if l.cache == nil {
		l.cache = map[int64]*dbmodels.Department{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *departmentLoaderBatch) keyIndex(l *DepartmentLoader, key int64) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *departmentLoaderBatch) startTimer(l *DepartmentLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *departmentLoaderBatch) end(l *DepartmentLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
